// Süper Lig takımları (favori takım seçimi için) — alfabetik sırada
export const TEAMS = [
  'Alanyaspor',
  'Amed Sportif Faaliyetler',
  'Başakşehir',
  'Beşiktaş',
  'Çaykur Rizespor',
  'Çorum FK',
  'Erzurumspor FK',
  'Eyüpspor',
  'Fenerbahçe',
  'Galatasaray',
  'Gaziantep FK',
  'Gençlerbirliği',
  'Göztepe',
  'Kasımpaşa',
  'Kocaelispor',
  'Konyaspor',
  'Samsunspor',
  'Trabzonspor',
]
